---
permalink: sg120-1200/reinstalling-sg120-and-sg1200-cover.html 
sidebar: sidebar 
keywords: storagegrid, sg120, sg1200, storage node, admin appliance, cover, install, installing, installation, reinstall, reinstalling, reinstallation 
summary: Retire la cubierta del aparato para acceder a los componentes internos para realizar tareas de mantenimiento y vuelva a colocarla cuando haya terminado. 
---
= Sustituir la cubierta SG120 y SG1200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Retire la cubierta del aparato para acceder a los componentes internos para realizar tareas de mantenimiento y vuelva a colocarla cuando haya terminado.



== Paso 1: Retirar la tapa

.Pasos
. Envuelva el extremo de la correa de una pulsera ESD alrededor de la muñeca y fije el extremo del clip a un suelo metálico para evitar descargas estáticas cuando trabaje dentro del aparato.
. link:reinstalling-sg120-and-sg1200-into-cabinet-or-rack.html["Retire el dispositivo del armario o rack"] para acceder a la cubierta superior.


. Desbloquea el pestillo de la tapa presionando el botón azul de bloqueo en la tapa del aparato.
+
image:../media/drw_s2025_cover_replace_ieops-2559.svg["Desbloqueo y extracción de la tapa del aparato"]

. Gire el pestillo hacia arriba y hacia atrás hacia la parte trasera del chasis del aparato hasta que se detenga; a continuación, levante con cuidado la cubierta del chasis y déjela a un lado.




== Paso 2: reinstalar la cubierta

.Pasos
. Con el pestillo de la cubierta abierto, alinea la cubierta sobre el chasis y bájala con cuidado.
. Gire el pestillo de la cubierta hacia adelante y hacia abajo hasta que se detenga y la cubierta se asiente completamente en el chasis. Compruebe que no hay separaciones a lo largo del borde delantero de la cubierta.
+
Si la cubierta no está completamente asentada, es posible que no pueda introducir el aparato en el rack.

. link:reinstalling-sg120-and-sg1200-into-cabinet-or-rack.html["Vuelva a instalar el aparato en el armario o rack"].

