---
sidebar: sidebar 
permalink: whats-new-appliances.html 
keywords: storagegrid, appliance, whats new 
summary: Conozca las novedades de este sitio de documentación. 
---
= Novedades en los dispositivos StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Conozca las novedades en los dispositivos StorageGRID .



== Aparatos de servicios SG120 y SG1200

Los nuevos dispositivos de servicios StorageGRID SG120 y SG1200 son una actualización de hardware evolutiva que proporciona un rendimiento administrativo y de equilibrio de carga mejorado. Consulta link:./installconfig/hardware-description-sg120-and-1200.html["Dispositivo de servicios SG120 y SG1200: descripción general"] para obtener más información.



== Dispositivo SGF6212

El nuevo dispositivo de almacenamiento StorageGRID SGF6212 presenta un diseño compacto con controlador informático y controlador de almacenamiento integrados en un chasis de 1U. El dispositivo admite 12 unidades SSD NVMe en un RAID que proporciona almacenamiento de objetos resistente. Consulta link:installconfig/hardware-description-sg6200.html["Aparato SGF6212: visión general"] para obtener más información.



== Dispositivo SG6260

El nuevo dispositivo StorageGRID SG6260 incluye un controlador informático y una bandeja de controlador de almacenamiento que contiene dos controladores de almacenamiento y 60 unidades, así como dos unidades SSD NVMe para caché. Opcionalmente, se pueden añadir bandejas de expansión de 60 unidades al SG6260. Consulta link:./installconfig/hardware-description-sg6200.html["Aparatos SGF6200: visión general"] para saber más.



== La red del cliente se puede configurar sin una dirección IP

Ahora puede habilitar la red de cliente sin especificar una dirección IP.  Esto permite que la red del cliente tenga interfaces VLAN configuradas en StorageGRID sin requerir una dirección IP adicional para la interfaz en sí. Consulte link:.//installconfig/setting-ip-configuration.html["Configure las direcciones IP de StorageGRID"] .



== Los números de versión del software StorageGRID y el instalador del dispositivo están alineados

Con la versión 12.0 de StorgeGRID, el número de versión del instalador del dispositivo StorageGRID coincide con la versión del software StorageGRID .  Los usuarios ya no necesitan averiguar qué versiones funcionan juntas. Consulte link:./installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["Comprobar y actualizar la versión de StorageGRID Appliance Installer"] .



== Información para BMC

Ahora está disponible información detallada sobre el uso de la interfaz BMC del dispositivo StorageGRID . Consulte link:./commonhardware/use-bmc.html["Utilice el controlador de gestión (BMC) de la placa base del dispositivo StorageGRID."] .
