---
permalink: sg6200/index.html 
sidebar: sidebar 
keywords: storagegrid, sg6200 storage appliance, SGF6212 storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: Es posible que necesites realizar procedimientos de mantenimiento en tu appliance. Los procedimientos específicos para el mantenimiento de tu appliance sg6200 se encuentran en esta sección. 
---
= Mantén el dispositivo SG6200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que necesites realizar procedimientos de mantenimiento en tu appliance. Los procedimientos específicos para el mantenimiento de tu appliance SG6200 se encuentran en esta sección.

En los procedimientos descritos en esta sección se asume que el dispositivo ya se ha puesto en marcha como nodo de almacenamiento en un sistema StorageGRID.

*Los procedimientos de configuración de mantenimiento* se realizan mediante el Instalador de dispositivos, Grid Manager o la interfaz de BMC. Estos procedimientos incluyen:

* link:turning-sg6200-identify-led-on-and-off.html["Encienda y apague el LED de identificación del aparato"]
* link:locating-sg6200-in-data-center.html["Localice el dispositivo en el centro de datos"]
* link:power-sg6200-off-on.html["Apague el aparato"]
* link:changing-link-configuration-of-sg6200-appliance.html["Cambie la configuración de enlace del dispositivo"]


*Los procedimientos de mantenimiento del hardware* requieren la manipulación física de componentes específicos SGF6212 o SG6260.



== Actualización del firmware de la unidad

El firmware de las unidades en el y SG6260 se comprueba automáticamente cada vez que se reinicia el dispositivo. Cuando es necesario, el firmware se actualiza automáticamente a la versión esperada por la versión actual de StorageGRID. Normalmente, las actualizaciones de firmware ocurren durante las actualizaciones de software de StorageGRID. Cualquier actualización necesaria del firmware de la unidad para las versiones existentes de StorageGRID se incluirá en correcciones urgentes. Sigue las instrucciones proporcionadas con cada corrección urgente para asegurarte de que la actualización se aplica a todas las unidades que podrían beneficiarse de ella.

Además, las unidades del SG6260 pueden actualizarse a través de SANtricity usando los procedimientos link:upgrading-drive-firmware-using-santricity-system-manager-online.html["SANtricity System Manager en línea"] o link:upgrading-drive-firmware-using-santricity-system-manager-offline.html["SANtricity System Manager fuera de línea"].


NOTE: SANtricity System Manager no es necesario para mantener el dispositivo SGF6212.



== Procedimientos generales de mantenimiento

Consulte link:../commonhardware/index.html["Procedimientos de mantenimiento comunes"] para procedimientos que son los mismos para todos los dispositivos, como aplicar una revisión, recuperar un nodo o sitio y realizar el mantenimiento de la red.

Consulte link:../installconfig/configuring-hardware.html["Configure el hardware del dispositivo"] para los procedimientos de mantenimiento del dispositivo que también se realizan durante la instalación y configuración inicial del dispositivo.
