---
permalink: installconfig/configuring-bmc-interface.html 
sidebar: sidebar 
keywords: BMC, baseboard management controller, configure, setup, set up 
summary: 'La interfaz de usuario para el baseboard management controller (BMC) en el SG6200, SG6100, SG6000 o appliance de servicios proporciona información de estado sobre el hardware y te permite configurar los ajustes de SNMP y otras opciones para los appliances.' 
---
= Interfaz BMC para dispositivos StorageGRID SG6000, SG6100 y SG6200 y dispositivos de servicios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz de usuario del controlador de gestión de placa base (BMC) proporciona información sobre el estado de tu hardware y permite el acceso a hardware de bajo nivel para la configuración, supervisión y diagnóstico del dispositivo.

Puedes usar el BMC para:

* Soluciona problemas de la instalación de hardware
* Configure los ajustes de SNMP
* Determina el estado de energía de tu appliance
* Controla el LED de identificación de tu appliance


Los siguientes dispositivos StorageGRID son compatibles con la interfaz BMC:

* SG100
* SG110
* SG120
* SG1000
* SG1100
* SG1200
* SGF6024
* SGF6112
* SGF6212
* SG6060
* SG6160
* SG6260


Si estás instalando tu dispositivo, usa los siguientes procedimientos para configurar el BMC:

* link:../installconfig/changing-root-password-for-bmc-interface.html["Cambie la contraseña de administrador o de raíz de la interfaz de BMC"]
* link:../installconfig/setting-ip-address-for-bmc-management-port.html["Establezca la dirección IP para el puerto de administración de BMC"]
* link:../installconfig/accessing-bmc-interface.html["Acceda a la interfaz de BMC"]
* link:../installconfig/configuring-snmp-settings-for-bmc.html["Configure los ajustes de SNMP"]
* link:../installconfig/setting-up-email-notifications-for-alerts.html["Configurar notificaciones por correo electrónico para las alertas de BMC"]


Si ya has instalado el dispositivo en una grid y está ejecutando el software StorageGRID, usa los siguientes procedimientos:

* link:../commonhardware/placing-appliance-into-maintenance-mode.html["Coloque el dispositivo en modo de mantenimiento"] Para acceder al instalador del dispositivo StorageGRID.
* Consulta link:../installconfig/setting-ip-address-for-bmc-management-port.html["Establezca la dirección IP para el puerto de administración de BMC"] para obtener información sobre cómo acceder a la interfaz BMC usando el StorageGRID Appliance Installer.


Para obtener más información sobre las funciones que puedes usar con el BMC después de haberlo configurado, consulta link:../commonhardware/use-bmc.html["Utilice la interfaz de BMC"] y la  https://kb.netapp.com/hybrid/StorageGRID/Platforms/How_to_use_StorageGRID_Appliance_BMC_with_vendor_supplied_user_guide["Guía del usuario de BMC"^].
