---
permalink: installconfig/monitoring-appliance-installation.html 
sidebar: sidebar 
keywords: appliance, installation, install, progress, monitor, status 
summary: El instalador del dispositivo StorageGRID proporciona el estado hasta que se completa la instalación. Una vez finalizada la instalación del software, el dispositivo se reinicia. 
---
= Supervise la instalación del dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El instalador del dispositivo StorageGRID proporciona el estado hasta que se completa la instalación. Una vez finalizada la instalación del software, el dispositivo se reinicia.

.Pasos
[role="tabbed-block"]
====
.Dispositivo de almacenamiento
--
. Para supervisar el progreso de la instalación, haga clic en *instalación del monitor*.
+
La página Monitor Installation (instalación del monitor) muestra el progreso de la instalación.

+
La barra de estado azul indica qué tarea está en curso actualmente. Las barras de estado verdes indican tareas que se han completado correctamente.

+

NOTE: Installer garantiza que las tareas completadas en una instalación anterior no se vuelvan a ejecutar. Si está volviendo a ejecutar una instalación, cualquier tarea que no necesite volver a ejecutarse se mostrará con una barra de estado verde y un estado de ''omitido''.

. Revise el progreso de las dos primeras etapas de instalación.
+
*1. Configurar almacenamiento*

+
En esta etapa, el instalador se conecta a la controladora de almacenamiento, borra cualquier configuración existente, crea raids según el modo RAID configurado, asigna volúmenes para el software StorageGRID y el almacenamiento de datos de objetos y configura los ajustes del host.

+
*2. Instalar OS*

+
Durante esta fase, el instalador copia la imagen del sistema operativo base para StorageGRID en el dispositivo.

. Continúe monitoreando el progreso de la instalación hasta que la etapa *Instalar StorageGRID* se pause y aparezca un mensaje en la consola integrada que le solicite que apruebe este nodo en el Nodo de administración mediante el Administrador de Grid; luego, vaya al siguiente paso.
. https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Vaya a Grid Manager"^]del nodo de administración principal, apruebe el nodo de almacenamiento pendiente y complete el proceso de instalación de StorageGRID .
+
Al hacer clic en *instalar* desde Grid Manager, se completa la fase 3 y comienza la fase 4, *Finalizar instalación*. Cuando finaliza la etapa 4, se reinicia la controladora.



Cierre la ventana una vez finalizadas todas las etapas de instalación.

--
.Dispositivo de servicios
--
. Para supervisar el progreso de la instalación, haga clic en *instalación del monitor*.
+
La página Monitor Installation (instalación del monitor) muestra el progreso de la instalación.

+
La barra de estado azul indica qué tarea está en curso actualmente. Las barras de estado verdes indican tareas que se han completado correctamente.

+

NOTE: Installer garantiza que las tareas completadas en una instalación anterior no se vuelvan a ejecutar. Si está volviendo a ejecutar una instalación, cualquier tarea que no necesite volver a ejecutarse se mostrará con una barra de estado verde y un estado de ''omitido''.

. Revise el progreso de las dos primeras etapas de instalación.
+
*1. Configurar almacenamiento*

+
Durante esta fase, el instalador borra toda la configuración existente de las unidades del dispositivo y configura la configuración del host.

+
*2. Instalar OS*

+
Durante esta fase, el instalador copia la imagen del sistema operativo base para StorageGRID en el dispositivo.

. Continúe supervisando el progreso de la instalación hasta que se produzca uno de los siguientes procesos:
+
** Para todos los nodos del dispositivo, excepto el nodo de administración principal, la etapa de instalación de StorageGRID se pausa y aparece un mensaje en la consola integrada que le solicita que apruebe este nodo en el nodo de administración mediante el botón https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Administrador de grid"^] ; luego, pase al siguiente paso.
** Para la instalación del nodo de administración principal del dispositivo, no es necesario aprobar el nodo. El dispositivo se reinicia. Puede omitir el paso siguiente.
+

NOTE: Durante la instalación de un nodo de administración principal del dispositivo, aparece una quinta fase para cargar el instalador de StorageGRID (la captura de pantalla de ejemplo muestra solo las primeras cuatro fases). Si se está cargando el instalador de StorageGRID (quinta fase) durante más de 10 minutos, actualice la página web manualmente.



. https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Vaya a Grid Manager"^] Del nodo de administración principal, apruebe el nodo de cuadrícula pendiente y complete el proceso de instalación de StorageGRID.
+
Al hacer clic en *instalar* desde Grid Manager, se completa la fase 3 y comienza la fase 4, *Finalizar instalación*. Cuando finalice la fase 4, el dispositivo se reiniciará.



Cierre la ventana una vez finalizadas todas las etapas de instalación.

--
====