---
permalink: installconfig/preparing-site.html 
sidebar: sidebar 
keywords: site prep, site preparation, preparing site, site requirements, requirements, site, dimensions, weight, weights, temperature, humidity, altitude, airflow, heat, wiring, power, grounding, facility 
summary: Antes de instalar el dispositivo, debe asegurarse de que el sitio y el armario o rack que desee usar cumplan con las especificaciones de un dispositivo StorageGRID. 
---
= Prepare el sitio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar el dispositivo, debe asegurarse de que el sitio y el armario o rack que desee usar cumplan con las especificaciones de un dispositivo StorageGRID.

.Pasos
. Confirmar que el emplazamiento cumple los requisitos de temperatura, humedad, rango de altitud, flujo de aire, disipación de calor, cableado, alimentación y conexión a tierra. Consulte https://hwu.netapp.com["Hardware Universe de NetApp"^] si quiere más información.
. Confirme que su ubicación proporciona el voltaje correcto de la alimentación de CA:
+
[cols="1a,1a"]
|===
| Modelo | Requisito 


 a| 
SG100 y SG1000
 a| 
120 a 240 voltios CA



 a| 
SG110 y SG1100
 a| 
100 a 240 voltios CA



 a| 
SG5760
 a| 
240 VOLTIOS CA



 a| 
SGF6024
 a| 
120 VOLTIOS CA



 a| 
SG6060
 a| 
240 VOLTIOS CA



 a| 
SGF6112
 a| 
100 a 240 voltios CA

|===
. Obtenga un armario o rack de 19 pulgadas (48,3 cm) para adaptarse a estantes del siguiente tamaño (sin cables).
+
[role="tabbed-block"]
====
.SG100 y SG1000
--
[cols="1a,1a,1a,1a"]
|===
| Altura | Anchura | Profundidad | Peso máximo 


 a| 
1,70 pda

(4,32 in)
 a| 
17,32 pda

(44,0 in)
 a| 
32,0 pda

(81,3 in)
 a| 
39 lb

(17,7 kg)

|===
--
.SG110 y SG1100
--
[cols="1a,1a,1a,1a"]
|===
| Altura | Anchura | Profundidad | Peso máximo 


 a| 
1,70 pda

(4,31 in)
 a| 
18,98 pda

(48,2 in)
 a| 
33,11 pda

(84,1 in)
 a| 
43,83 lb

(19,88 kg)

|===
--
.SG5700
--
[cols="1a,1a,1a,1a,1a"]
|===
| Modelo de dispositivo | Altura | Anchura | Profundidad | Peso máximo 


 a| 
SG5712

(12 unidades)
 a| 
3,41 pda

(8,68 in)
 a| 
17,6 pda

(44,7 in)
 a| 
21,1 pda

(53,6 in)
 a| 
63.9 lb

(29,0 kg)



 a| 
SG5760

(60 unidades)
 a| 
6,87 pda

(17,46 in)
 a| 
17,66 pda

(44,86 in)
 a| 
38,25 pda

(97,16 in)
 a| 
250 lb

(113 kg)

|===
--
.SG6000
--
[cols="2a,1a,1a,1a,1a"]
|===
| Tipo de bandeja | Altura | Anchura | Profundidad | Peso máximo 


 a| 
Bandeja de controladora E2860 (SG6060)
 a| 
6,87 pda

(17,46 in)
 a| 
17,66 pda

(44,86 in)
 a| 
38,25 pda

(97,16 in)
 a| 
250 lb

(113 kg)



 a| 
Bandeja de expansión (SG6060): Opcional
 a| 
6,87 pda

(17,46 in)
 a| 
17,66 pda

(44,86 in)
 a| 
38,25 pda

(97,16 in)
 a| 
250 lb

(113 kg)



 a| 
Bandeja de controladora EF570 (SGF6024)
 a| 
3,35 pda

(8,50 in)
 a| 
17,66 pda

(44,86 in)
 a| 
19,00 pda

(48,26 in)
 a| 
51.74 lb.

(23,47 kg)



 a| 
Controladora de computación SG6000-CN
 a| 
1,70 pda

(4,32 in)
 a| 
17,32 pda

(44,0 in)
 a| 
32,0 pda

(81,3 in)
 a| 
39 lb

(17,7 kg)

|===
--
.SG6100
--
[cols="1a,1a,1a,1a"]
|===
| Altura | Anchura | Profundidad | Peso máximo 


 a| 
1,70 pda

(4,31 in)
 a| 
18,98 pda

(48,2 in)
 a| 
33,11 pda

(84,1 in)
 a| 
43,83 lb

(19,88 kg)

|===
--
====
. Decida dónde va a instalar el aparato.
+

CAUTION: Al instalar la bandeja de controladoras E2860 o las bandejas de expansión opcionales, instale el hardware desde la parte inferior hasta la parte superior del rack o armario para evitar que el equipo se vuelque. Para garantizar que el equipo más pesado se encuentra en la parte inferior del armario o bastidor, instale el controlador SG6000-CN encima de la bandeja de controladores E2860 y las bandejas de expansión.

+

NOTE: Antes de realizar la instalación, compruebe que los cables ópticos 0,5m que se suministran con un dispositivo SG6000 o los cables que suministre sean lo suficientemente largos para el diseño planificado.

. Instale los switches de red necesarios. Consulte link:https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] para obtener información sobre compatibilidad.

