---
permalink: installconfig/reviewing-appliance-network-connections.html 
sidebar: sidebar 
keywords: network connections, appliance, grid, admin, client, bmc, management 
summary: Antes de instalar el dispositivo StorageGRID, debe saber qué redes se pueden conectar al dispositivo. 
---
= Tipos de red StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar el dispositivo StorageGRID, debe comprender qué redes se pueden conectar al dispositivo y cómo se utilizan los puertos de cada controladora. Los requisitos de red de StorageGRID se explican en detalle en la https://docs.netapp.com/us-en/storagegrid-118/network/index.html["Directrices sobre redes"^].

Consulte las instrucciones de su aparato para determinar la información que necesita:

* link:gathering-installation-information-sg100-and-sg1000.html["SG100 y SG1000"]
* link:gathering-installation-information-sg5700.html["SG5700"]
* link:gathering-installation-information-sg6000.html["SG6000"]
* link:gathering-installation-information-sg6100.html["SG6100"]


También puede trabajar con su asesor de servicios profesionales de NetApp para utilizar la herramienta ConfigBuilder de NetApp para optimizar y automatizar los pasos de configuración. Consulte link:automating-appliance-installation-and-configuration.html["Automatice la instalación y configuración de los dispositivos"].

Cuando implementa un dispositivo StorageGRID como nodo en un sistema StorageGRID, puede conectarlo a las siguientes redes:

* *Red de Grid para StorageGRID*: La red de red se utiliza para todo el tráfico interno de StorageGRID. Proporciona conectividad entre todos los nodos de la cuadrícula, en todos los sitios y subredes. Se requiere la red de red.
* *Red de administración para StorageGRID*: La Red de administración es una red cerrada que se utiliza para la administración y el mantenimiento del sistema. La red de administración suele ser una red privada y no es necesario que se pueda enrutar entre sitios. La red administrativa es opcional.
* *Red de clientes para StorageGRID:* la red de clientes es una red abierta que se utiliza para proporcionar acceso a las aplicaciones cliente, incluidos S3 y Swift. La red de cliente proporciona acceso de protocolo de cliente a la cuadrícula, de modo que la red de red de red pueda aislarse y protegerse. Puede configurar la red de cliente de modo que se pueda acceder al dispositivo a través de esta red utilizando sólo los puertos que elija abrir. La red cliente es opcional.
* *Red de gestión para SANtricity* (opcional para dispositivos de almacenamiento, no necesario para el SG6100): Esta red proporciona acceso al Administrador del sistema de SANtricity, lo que le permite supervisar y gestionar los componentes de hardware en el dispositivo y el estante del controlador de almacenamiento. Esta red de gestión puede ser la misma que la Red de administración para StorageGRID, o bien puede ser una red de gestión independiente.
* *Red de gestión BMC* (opcional para SG100, SG1000, SG6000 y SG6100): Esta red proporciona acceso al controlador de administración de placa base en los dispositivos SG100, SG1000, SG6000 y SG6100, lo que le permite supervisar y administrar los componentes de hardware en el dispositivo. Esta red de gestión puede ser la misma que la Red de administración para StorageGRID, o bien puede ser una red de gestión independiente.
+
Si la red de administración opcional de BMC no está conectada, será más difícil realizar algunos procedimientos de soporte y mantenimiento. Puede dejar la red de gestión de BMC sin conexión excepto cuando sea necesario para fines de soporte.




NOTE: Para obtener información detallada sobre las redes StorageGRID, consulte https://docs.netapp.com/us-en/storagegrid-118/network/storagegrid-network-types.html["Tipos de red StorageGRID"^].
