---
permalink: installconfig/verifying-port-level-network-connections.html 
sidebar: sidebar 
keywords: network connections, network connection, network, connection, connectivity, verify, verifying, check, checking, ports, port, port-level, port level, test, testing, udp, Client Network, Admin Network 
summary: Para garantizar que los firewalls no obstruyan el acceso entre el instalador del dispositivo StorageGRID y otros nodos, confirme que el instalador del dispositivo StorageGRID puede conectarse a un puerto TCP o a un conjunto de puertos en la dirección IP o el rango de direcciones especificados. 
---
= Verifique las conexiones de red a nivel de puerto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para garantizar que los firewalls no obstruyan el acceso entre el instalador del dispositivo StorageGRID y otros nodos, confirme que el instalador del dispositivo StorageGRID puede conectarse a un puerto TCP o a un conjunto de puertos en la dirección IP o el rango de direcciones especificados.

.Acerca de esta tarea
Con la lista de puertos que se incluye en el instalador de dispositivos de StorageGRID, puede probar la conectividad entre el dispositivo y los demás nodos de la red de grid.

Además, puede probar la conectividad en las redes de administración y cliente y en los puertos UDP, como los que se utilizan para servidores NFS o DNS externos. Para obtener una lista de estos puertos, consulte la https://docs.netapp.com/us-en/storagegrid/network/network-port-reference.html["referencia de puerto de red"^].


NOTE: Los puertos de red de grid que aparecen en la tabla de conectividad de puertos son válidos sólo para StorageGRID versión 11,7 o posterior. Para verificar qué puertos son correctos para cada tipo de nodo, siempre debe consultar las directrices de red para su versión de StorageGRID.

.Pasos
. En el instalador del dispositivo StorageGRID, haga clic en *Configurar red* > *Prueba de conectividad de puerto (nmap)*.
+
Aparece la página Prueba de conectividad de puerto.

+
La tabla de conectividad de puertos enumera los tipos de nodos que requieren conectividad TCP en la red de cuadrícula. Para cada tipo de nodo, la tabla enumera los puertos de red de cuadrícula a los que el dispositivo debe acceder.

+
Puede probar la conectividad entre los puertos del dispositivo que aparecen en la tabla y los demás nodos de la red de grid.

. En el menú desplegable *Red*, seleccione la red que desea probar: *Grid*, *Admin* o *Cliente*.
. Especifique una lista separada por espacios o un rango de direcciones IPv4 para los hosts en esa red.
. Introduzca un número de puerto TCP, una lista de puertos separados por comas o un intervalo de puertos.
. Haga clic en *probar conectividad*.
+
** Si las conexiones de red a nivel de puerto seleccionadas son válidas, aparece el mensaje "`Prueba de conectividad de puerto aprobada`" en un banner verde.  La salida del comando nmap se muestra debajo del banner.  Los hosts inalcanzables no aparecerán en la salida del comando nmap.
** Si se establece una conexión de red a nivel de puerto con el host remoto, pero el host no está escuchando en uno o más de los puertos seleccionados, aparece el mensaje "`Error en la prueba de conectividad del puerto`" en un banner amarillo.  La salida del comando nmap se muestra debajo del banner.  Los hosts inalcanzables no aparecerán en la salida del comando nmap.
+
Cualquier puerto remoto al que no esté escuchando el host tiene un estado de "'cerrado'". Por ejemplo, puede ver este banner amarillo cuando el nodo al que intenta conectarse está en estado preinstalado y el servicio NMS de StorageGRID aún no se está ejecutando en ese nodo.

** Si no se puede realizar una conexión de red a nivel de puerto para uno o más puertos seleccionados, aparece el mensaje "`Error en la prueba de conectividad del puerto`" en un banner rojo.  La salida del comando nmap se muestra debajo del banner.  Los hosts inalcanzables no aparecerán en la salida del comando nmap.
+
El banner rojo indica que se ha realizado un intento de conexión TCP a un puerto en el host remoto, pero no se ha devuelto nada al remitente. Cuando no se devuelve ninguna respuesta, el puerto tiene un estado de "filtrado" y es probable que sea bloqueado por un firewall.

+

NOTE: También se enumeran los puertos con «'cerrado'».




