= Paso 1: quitar la NIC
:allow-uri-read: 




== Paso 1: quitar la NIC

[role="tabbed-block"]
====
.NIC 1/NIC 2
--
.Pasos
. Envuelva el extremo de la correa de la muñequera ESD alrededor de su muñeca y fije el extremo de la pinza a una masa metálica para evitar descargas estáticas.
. Localice el conjunto elevador que contiene la NIC en la parte posterior del aparato.
. Gira el pestillo de bloqueo azul del elevador con la NIC averiada hacia arriba y ábrelo.
+
image:../media/drw_s2025_io_1_2_replace_ieops-2555.svg["Extracción de NIC 1 o NIC 2 del conjunto del elevador"]

. Levanta con cuidado el conjunto del elevador con la NIC averiada utilizando los orificios marcados en azul. Mueve el conjunto del elevador hacia la parte frontal del chasis mientras lo levantas para permitir que los conectores externos de la NIC instalada salgan del chasis.
. Coloca el elevador sobre una superficie plana antiestática con el marco metálico hacia abajo para acceder a la NIC.
. Abre el pestillo azul de la tarjeta NIC averiada y extráela con cuidado del conjunto del elevador. Balancea ligeramente la tarjeta NIC para ayudar a extraerla de su conector. No uses fuerza excesiva.
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["Extracción de una tarjeta IO del conjunto elevador"]

. Coloca el riser y la NIC sobre una superficie plana antiestática.


--
.NIC 3
--
.Pasos
. Envuelva el extremo de la correa de la muñequera ESD alrededor de su muñeca y fije el extremo de la pinza a una masa metálica para evitar descargas estáticas.
. Gira el bloqueo azul del elevador con la NIC averiada a la posición abierta.
+
image:../media/drw_s2025_io_3_replace_ieops-2556.svg["Extracción de la NIC 3 del conjunto del elevador"]

. Levanta con cuidado el ensamblaje del elevador hacia arriba usando el orificio marcado en azul y el borde del elevador. Mueve el ensamblaje del elevador hacia la parte frontal del chasis mientras lo levantas para permitir que los conectores externos de la NIC instalada salgan del chasis.
. Coloca el elevador sobre una superficie plana antiestática con el marco metálico hacia abajo para acceder a la NIC.
. Abre el pestillo azul de la tarjeta NIC averiada y extráela con cuidado del conjunto del elevador. Balancea ligeramente la tarjeta NIC para ayudar a extraerla de su conector. No uses fuerza excesiva.
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["Extracción de una tarjeta IO del conjunto elevador"]

. Coloca el riser y la NIC sobre una superficie plana antiestática.


--
====


== Paso 2: reinstalar el NIC interno

Instale la NIC de reemplazo en la misma ubicación que la que se quitó.

[role="tabbed-block"]
====
.NIC 1/NIC 2
--
.Pasos
. Envuelva el extremo de la correa de la muñequera ESD alrededor de su muñeca y fije el extremo de la pinza a una masa metálica para evitar descargas estáticas.
. Retire la NIC de repuesto de su embalaje.
. Instala la NIC de repuesto en el conjunto del elevador.
+
.. Asegúrese de que el pestillo azul está en la posición abierta.
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["Instalar una tarjeta IO en el conjunto elevador"]

.. Alinea la NIC con su conector en el conjunto del elevador. Presiona con cuidado la NIC en el conector hasta que quede completamente asentada y luego cierra el pestillo azul.


. Vuelve a instalar el conjunto del elevador en el chasis.
+
.. Localiza el orificio de alineación en el ensamblaje del elevador que se alinea con un pasador guía en la placa del sistema para asegurar la correcta colocación del ensamblaje del elevador.
+
image:../media/drw_s2025_io_1_2_reinstall_ieops-2685.svg["Sustitución de NIC 1 o NIC 2 en el conjunto del elevador"]

.. Coloque el conjunto de elevador en el chasis, asegurándose de que esté alineado con el conector de la placa del sistema y el pasador guía.
.. Presione con cuidado el conjunto de la tarjeta vertical en su lugar a lo largo de su línea central, junto a los orificios marcados en azul, hasta que esté completamente asentado.


. Si no tiene que realizar ningún otro procedimiento de mantenimiento en el aparato, vuelva a instalar la cubierta del aparato, vuelva a colocar el aparato en el bastidor, conecte los cables y conecte la alimentación.


Después de sustituir la pieza, devuelve la pieza defectuosa a NetApp, como se describe en las instrucciones de RMA enviadas con el kit. Consulta la  https://mysupport.netapp.com/site/info/rma["Devolución de piezas  sustituciones"^] página para más información.

--
.NIC 3
--
.Pasos
. Envuelva el extremo de la correa de la muñequera ESD alrededor de su muñeca y fije el extremo de la pinza a una masa metálica para evitar descargas estáticas.
. Retire la NIC de repuesto de su embalaje.
. Instala la NIC de repuesto en el conjunto del elevador.
+
.. Asegúrese de que el pestillo azul está en la posición abierta.
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["Instalar una tarjeta IO en el conjunto elevador"]

.. Alinea la NIC con su conector en el conjunto del elevador. Presiona con cuidado la NIC en el conector hasta que quede completamente asentada y luego cierra el pestillo azul.


. Vuelve a instalar el conjunto del elevador en el chasis.
+
.. Coloca el conjunto del elevador en el chasis, asegurándote de que los bordes del conjunto del elevador se alineen correctamente con los bordes del chasis.
+
image:../media/drw_s2025_IO_3_replace_ieops-2686.svg["Sustitución de NIC 3 en el conjunto del riser"]

.. Presiona con cuidado el conjunto del elevador en su lugar a lo largo de su línea central, junto al orificio marcado en azul, hasta que esté completamente asentado.
.. Gira el cierre azul del elevador a la posición de cerrado.


. Retire las tapas protectoras de los puertos NIC en los que va a volver a instalar los cables.
. Si no tiene que realizar ningún otro procedimiento de mantenimiento en el aparato, vuelva a instalar la cubierta del aparato, vuelva a colocar el aparato en el bastidor, conecte los cables y conecte la alimentación.


Después de sustituir la pieza, devuelve la pieza defectuosa a NetApp, como se describe en las instrucciones de RMA enviadas con el kit. Consulta la  https://mysupport.netapp.com/site/info/rma["Devolución de piezas  sustituciones"^] página para más información.

--
====