---
permalink: sg6100/index.html 
sidebar: sidebar 
keywords: storagegrid, sg6100 storage appliance, SGF6112 storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: Es posible que necesite realizar procedimientos de mantenimiento en el aparato. Los procedimientos específicos para el mantenimiento de su aparato SG6100 se encuentran en esta sección. 
---
= Mantenimiento del dispositivo SG6100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que necesite realizar procedimientos de mantenimiento en el aparato. Los procedimientos específicos para el mantenimiento de su aparato SG6100 se encuentran en esta sección.

En los procedimientos descritos en esta sección se asume que el dispositivo ya se ha puesto en marcha como nodo de almacenamiento en un sistema StorageGRID.

*Los procedimientos de configuración de mantenimiento* se realizan mediante el Instalador de dispositivos, Grid Manager o la interfaz de BMC. Estos procedimientos incluyen:

* link:turning-sgf6112-identify-led-on-and-off.html["Encienda y apague el LED de identificación del aparato"]
* link:locating-sgf6112-in-data-center.html["Localice el dispositivo en el centro de datos"]
* link:power-sgf6112-off-on.html["Apague el aparato"]
* link:changing-link-configuration-of-sgf6112-appliance.html["Cambie la configuración de enlace del dispositivo"]


*Los procedimientos de mantenimiento del hardware* requieren la manipulación física de componentes específicos de SGF6112.



== Actualización del firmware de la unidad

El firmware de las unidades en el SGF6112 se comprueba automáticamente cada vez que se reinicia el dispositivo. Cuando es necesario, el firmware se actualiza automáticamente a la versión esperada por la versión de StorageGRID actual. En general, las actualizaciones de firmware se producen durante las actualizaciones del software StorageGRID. Todas las actualizaciones de firmware de la unidad necesarias para versiones de StorageGRID existentes se incluirán en las correcciones urgentes. Siga las instrucciones proporcionadas con cada revisión para asegurarse de que la actualización se aplica a todas las unidades que podrían beneficiarse de ella.


NOTE: No es necesario SANtricity System Manager para mantener el dispositivo SGF6112.



== Procedimientos generales de mantenimiento

Consulte link:../commonhardware/index.html["Procedimientos de mantenimiento comunes"] para procedimientos que son los mismos para todos los dispositivos, como aplicar una revisión, recuperar un nodo o sitio y realizar el mantenimiento de la red.

Consulte link:../installconfig/configuring-hardware.html["Configure el hardware del dispositivo"] para los procedimientos de mantenimiento del dispositivo que también se realizan durante la instalación y configuración inicial del dispositivo.
