---
permalink: sg5800/index.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Mantenimiento del dispositivo SG5800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede que deba actualizar el software de sistema operativo SANtricity en la controladora E4000, cambiar la configuración del enlace Ethernet de la controladora SG5800, reemplazar la controladora E4000 o la controladora SG5800, o sustituir componentes específicos. En los procedimientos descritos en esta sección se asume que el dispositivo ya se ha puesto en marcha como nodo de almacenamiento en un sistema StorageGRID.

Los procedimientos específicos para el mantenimiento de su aparato SG5800 se encuentran en esta sección.

Consulte link:../commonhardware/index.html["Procedimientos comunes"] para los procedimientos de mantenimiento que utilizan todos los aparatos.

Consulte link:../installconfig/configuring-hardware.html["Configure el hardware"] para los procedimientos de mantenimiento que también se realizan durante la instalación y configuración inicial del dispositivo.
