---
permalink: commonhardware/considerations-and-requirements-for-appliance-node-cloning.html 
sidebar: sidebar 
keywords: storagegrid, clone appliance node, cloning appliance node 
summary: Antes de clonar un nodo de dispositivo, debe comprender las consideraciones y los requisitos. 
---
= Consideraciones y requisitos para el clonado de nodos de dispositivos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de clonar un nodo de dispositivo, debe comprender las consideraciones y los requisitos.


TIP: La clonación de nodos está deshabilitada para los nodos de puerta de enlace.  Para reemplazar un nodo de puerta de enlace, desactívelo y luego realice una expansión para agregar un nuevo nodo de puerta de enlace del dispositivo.  El procedimiento de desmantelamiento y expansión es mucho más rápido para un nodo de puerta de enlace que para un nodo de almacenamiento.



== Requisitos de hardware para el dispositivo de sustitución

Asegúrese de que el aparato de sustitución cumple los siguientes criterios:

* El nodo de origen (dispositivo que se va a reemplazar) y el dispositivo de destino (nuevo) deben ser del mismo tipo de dispositivo:
+
** Solo se puede clonar un dispositivo de nodo de administración en un nuevo dispositivo de servicios.
** Solo puede clonar un dispositivo Storage Node en un dispositivo de almacenamiento nuevo.


* Para un dispositivo de nodo de administración, no es necesario que el dispositivo del nodo de origen y el dispositivo de destino sean del mismo modelo; sin embargo, cambiar el modelo del dispositivo puede requerir reemplazar los cables o los módulos SFP.
+
Por ejemplo, puede sustituir un dispositivo de nodo SG1000 por un SG100 o sustituir un dispositivo SG100 por un dispositivo SG1000.

* Para los dispositivos Storage Node, el dispositivo del nodo de origen y el dispositivo de destino no necesitan ser del mismo tipo de dispositivo; sin embargo:
+
** El dispositivo objetivo debe tener mayor capacidad de almacenamiento que el dispositivo de origen.
+
Por ejemplo, puede reemplazar un dispositivo de nodos SG5700 por un dispositivo SG6000.

** El dispositivo objetivo debe tener una cantidad de volúmenes de almacenamiento de objetos igual o superior a la del dispositivo de origen.
+
Por ejemplo, no se puede reemplazar un dispositivo de nodo SG6000 (16 volúmenes de almacenamiento de objetos) con un dispositivo SGF6112 (12 volúmenes de almacenamiento de objetos).





Póngase en contacto con su representante de ventas de StorageGRID, para obtener ayuda a la hora de elegir dispositivos de reemplazo compatibles para clonar nodos de dispositivos específicos en la instalación de StorageGRID.



== Prepare para clonar un nodo de dispositivo

Debe tener la siguiente información antes de clonar un nodo de dispositivo:

* Obtenga una dirección IP temporal para la red de red de su administrador de red para utilizarla con el dispositivo de destino durante la instalación inicial. Si el nodo de origen pertenece a una red de administrador o una red de cliente, obtenga direcciones IP temporales para estas redes.
+
Las direcciones IP temporales suelen estar en la misma subred que el dispositivo de nodo de origen que se clona y no son necesarias una vez finalizada la clonación. Los dispositivos de origen y destino deben conectarse al nodo de administrador principal de la StorageGRID para establecer una conexión de clonado.

* Determine qué red se utilizará para clonar tráfico de transferencia de datos que ofrezca el mejor rendimiento de transferencia de datos sin perjudicar el rendimiento de la red de StorageGRID ni la disponibilidad de los datos.
+

NOTE: El uso de la red de administrador de 1 GbE para la transferencia de datos de clones provoca una clonación más lenta.

* Determine si utilizará el cifrado de nodo mediante un servidor de administración de claves (KMS) en el dispositivo de destino, de modo que pueda habilitar el cifrado de nodo durante la instalación inicial del dispositivo de destino antes de la clonación.  Puede verificar si el cifrado de nodo está habilitado en el nodo del dispositivo de origen como se describe enlink:../installconfig/optional-enabling-node-encryption.html["habilitar el cifrado de nodo"] .
+
El nodo de origen y el dispositivo de destino pueden tener diferentes configuraciones de cifrado de nodo con las siguientes excepciones.  No se admite la clonación de nodos desde orígenes de nodos no cifrados a destinos con nodos cifrados para los siguientes dispositivos:

+
** Un dispositivo de nodo SGF6112 sin cifrado de nodo a un dispositivo SGF6112 con cifrado de nodo
** Un dispositivo de nodo SG1100 sin cifrado de nodo a un dispositivo SG1100 con cifrado de nodo
** Un dispositivo de nodo SG110 sin cifrado de nodo a un dispositivo SG110 con cifrado de nodo


+
El cifrado y descifrado de datos se realiza automáticamente durante la transferencia de datos y cuando el nodo de destino se reinicia y se une a la red.

* Determine si el modo RAID del dispositivo de destino debe cambiarse desde su configuración predeterminada, por lo que puede especificar esta información durante la instalación inicial del dispositivo de destino antes de realizar la clonación. Puede ver información acerca del modo RAID actual del nodo del dispositivo de origen en la página *NODES* de Grid Manager. Seleccione la pestaña *Hardware* del aparato.
+
El nodo de origen y el dispositivo de destino pueden tener diferentes ajustes de RAID.

* Planifique el tiempo suficiente para completar el proceso de clonación de nodos. Es posible que se necesiten varios días para transferir datos desde un nodo de almacenamiento operativo a un dispositivo de destino. Programe la clonación en el momento que minimice el impacto en su negocio.
* Solo debe clonar un nodo de dispositivo cada vez. La clonado puede evitar que ejecute otras funciones de mantenimiento de StorageGRID al mismo tiempo.
* Después de clonar un nodo de dispositivo, puede usar el dispositivo de origen que volvió a su estado de instalación previa como destino para clonar otro dispositivo de nodo compatible.

