---
permalink: commonhardware/locate-mac-address.html 
sidebar: sidebar 
keywords: storagegrid, mac, mac address 
summary: En algunos casos, es posible que necesite actualizar las referencias de direcciones MAC después de reemplazar un dispositivo. 
---
= Actualizar referencias de direcciones MAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En algunos casos, es posible que necesite actualizar las referencias de direcciones MAC después de reemplazar un dispositivo.

.Acerca de esta tarea
Si alguna de las interfaces de red de un dispositivo que va a sustituir está configurada para DHCP, es posible que deba actualizar las asignaciones de permisos DHCP permanentes en los servidores DHCP para hacer referencia a las direcciones MAC del dispositivo de reemplazo. La actualización garantiza que el dispositivo de reemplazo tenga asignadas las direcciones IP esperadas.

.Pasos
. Localice la etiqueta en la parte frontal del aparato. La etiqueta enumera la dirección MAC del puerto de gestión BMC del dispositivo.
. Para determinar la dirección MAC del puerto de red de administración, debe agregar *2* al número hexadecimal de la etiqueta.
+
Por ejemplo, si la dirección MAC de la etiqueta termina en *09*, la dirección MAC del puerto de administración finalizará en *0B*. Si la dirección MAC de la etiqueta termina en *(_y_)FF*, la dirección MAC del puerto de administración finalizará en *(_y_+1)01*.

+
Puede realizar este cálculo fácilmente abriendo Calculadora en Windows, establecerlo en modo Programador, seleccionando hex, escribiendo la dirección MAC y, a continuación, escribiendo *+ 2 =*.

. Solicite al administrador de red que asocie el DNS/red y la dirección IP del dispositivo que ha quitado con la dirección MAC del dispositivo de reemplazo.
+

CAUTION: Debe asegurarse de que todas las direcciones IP del dispositivo original se han actualizado antes de aplicar alimentación al dispositivo de sustitución. De lo contrario, el dispositivo obtendrá nuevas direcciones IP de DHCP cuando se arranca y es posible que no pueda volver a conectarse a StorageGRID. Este paso se aplica a todas las redes StorageGRID conectadas al dispositivo.

+

NOTE: Si el dispositivo original utilizaba una dirección IP estática, el dispositivo nuevo adoptará automáticamente las direcciones IP del dispositivo que ha quitado.


